name: ritehand
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_reorderable_list: ^1.3.1

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Light.ttf
          weight: 300
  assets:
    - assets/images/